### ISSUE TITLE
`debounce` function behaving in non-standard way

### ISSUE THREAD

**Issue by jon-loubert** [blinkk/degu#164]
It's not quite a bug, but the `debounce` function (https://github.com/blinkk/degu/blob/main/src/func/func.ts#L30) behaves differently than what debounce functions usually do. 

Usually, the goal is to call the function once after X seconds, and all subsequent calls should restart the timer, such that the function is only invoked X seconds after the *last* call. The current behavior is to always call the function X seconds after the *first* call.

The minimal "fix" would be to change 
```js
if (!immediate && timeOutId === undefined) {
  timeOutId = +setTimeout(runLater, wait);
}
```
to
```js
if (!immediate) {
  if (timeOutId) {
    clearTimeout(timeOutId);
  }
  timeOutId = +setTimeout(runLater, wait);
}
```

but I'm not sure what the best approach is, i.e. if this new behaviour should replace the old, or if it should be gated behind a parameter...and it also might affect the related `throttle` function.

**Comment by uxder** [comment]
Thanks for reporting this @jon-loubert 

I pushed a fix for this.
